substitutions:
  name: bedroom-switch
  friendly_name: Bedroom Switch
  hass_entity_single_press_toggle: light.bedroom_group
  hass_entity_double_press_toggle: switch.adaptive_lighting_bedroom
  hass_entity_hold_toggle: switch.adaptive_lighting_sleep_mode

# COMMENT FOR MINIMAL
packages:
  Kauf.RGBSw:
    url: https://github.com/claudiosv/kauf-rgb-switch
    ref: main
    files: [kauf-rgbs.yaml]
    refresh: always

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# external_components:
#   - source:
#       type: git
#       url: https://github.com/KaufHA/common
#       ref: main
#     refresh: always
# api:
#   encryption:
#     key: H0whu0Cv4x6wF/pjhuomvHfKTRsCkFs505sxZ5CQX6k=

# UNCOMMENT FOR MINIMAL
# https://esphome.io/components/esp8266.html
# esp8266:
#   board: esp01_1m
#   restore_from_flash: true
#   early_pin_init: false
# esphome:
#   name: ${name}
#   name_add_mac_suffix: false
#   project:
#     name: Kauf.RGBSw
#     version: "0.1"
# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   output_power: 17
#   fast_connect: true
#   ap:
# captive_portal: # https://esphome.io/components/captive_portal.html
# logger: # https://esphome.io/components/logger.html
# api: # https://esphome.io/components/api.html
# ota: # https://esphome.io/components/ota.html
# web_server: # https://esphome.io/components/web_server.html
